### ISSUE TITLE
Package doesn't work

### ISSUE THREAD

**Issue by kevohagan** [amrali/parsleyjs-meteor#1]
Your references are not working. 
installing from mrt you get : 

```
error: File not found: parsleyjs/parsley.js
error: File not found: parsleyjs/parsley.extend.js
```

**Comment by amrali** [comment]
I've done the following against Meteor v0.7.0.1 and Meteorite v0.6.16:

```
meteor create test; cd test
mrt add parsley.js
```

and `parsley.js.js` was indeed in the page source and there were no errors. I'm unable to reproduce the problem.

Can you provide more details to reproduce the problem?

**Comment by mitchos** [comment]
The issue is that mrt clones the source from git and when cloning this repository manually, the parsley.js link doesn't get cloned as well. If you check your .meteorite/packages/parsley.js folder you will find that the parsley.js folder within is empty. 

Simply clone parsley.js into there and you will have it working.

**Comment by amrali** [comment]
@mitchos Do you mean this?
~/.meteorite/packages/parsley.js/amrali/parsleyjs-meteor/79c55fe96817d6209278ab90dcb3773ee854709a/parsley.js

Can you please provide Meteor and Meteorite version information, also type and version of the operating system you are using?

I've got a friend to test it for me and we are still unable to reproduce the problem.

**Comment by mitchos** [comment]
Yep, when I manually cloned the Parsley.js repo into the parsleyjs folder then I was able to correctly install with 'mrt add parsley.js'. 

Working filestructure is attached:

![image](https://f.cloud.github.com/assets/5283964/1948981/21fb1e74-80d1-11e3-865d-503d128fc3eb.png)

**Comment by amrali** [comment]
I see now. You don't have to manually clone it into that folder. You just have to do `git submodule update --init` from inside the root directory of `parsleyjs-meteor`. Also you only have to do this IFF you are planning to work on this repository. The canonical way of installing this package is to simply run `mrt add parsley.js` from your Meteor app directory as this package is hosted on Atmosphere (https://atmosphere.meteor.com/package/parsley.js).

**Comment by mitchos** [comment]
I think this might be an actual issue with meteorite with respect to git submodules, I originally used `mrt add parsley.js` and the `parsleyjs` folder gets created but is empty - the only thing in there are the package files e.g. `smart.json`. I see other people are having similar issues with meteorite and submodules so could be related.

**Comment by amrali** [comment]
I've stumbled on a few threads like that on the interwebs, it must be due to an old version; I never had this problem with Meteorite.

**Comment by kevohagan** [comment]
Yes, that is exactly what happens Mitch.
It's definitely not your falt Ali, but maybe you should put a comment in
your readme specifying the issue and what to do :)

Thanks a million for the package!

On 19 January 2014 07:57, Amr Ali notifications@github.com wrote:

> I've stumbled on a few threads like that on the interwebs, it must be due
> to an old version; I never had this problem with Meteorite.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/amrali/parsleyjs-meteor/issues/1#issuecomment-32702530
> .

## 

Kevin O'Hagan
+0034685245319
Palma de Mallorca,
Spain

**Comment by northcoders-chris** [comment]
What package should be used? none seem to work
I get an type error in one then just nothing happening in another
