### ISSUE TITLE
Error Building

### ISSUE THREAD

**Issue by edwardbc** [amrali/parsleyjs-meteor#2]
After executing `mrt add parsley.js`  i got the following message

=> Errors while scanning packages:

While building package `parsley.js`:
error: File not found: parsleyjs/parsley.js
error: File not found: parsleyjs/parsley.extend.js

**Comment by amrali** [comment]
Please see issue #1 and the relevant update to README.md. If that doesn't solve your problem, do let me know.

**Comment by edwardbc** [comment]
Oh I missed that issue! (I'm not expecting to work with the repo but well) Thanks!
