### ISSUE TITLE
Error while building package

### ISSUE THREAD

**Issue by vqc** [amrali/parsleyjs-meteor#4]
I get the following error after installing the most recent version of this package:

=> Errors while scanning packages:                                                                                                 

While building package `parsley.js`:  
parsley.remote.min.js:6:1: Unexpected token <

**Comment by amrali** [comment]
Make sure that you delete the cached versions from `~/.meteorite/source/amrali` and `~/.meteorite/packages/parsley.js` so that `mrt add parsley.js` pulls the source from the repository instead.

**Comment by vqc** [comment]
Thank you very much!
