### ISSUE TITLE
Use jquery in package

### ISSUE THREAD

**Issue by Neobii** [amrali/parsleyjs-meteor#5]
Package should look like this right?  I'm seeing a $.extend is not defined.

``` javascript
Package.describe({
  summary: "Javascript forms validation. Powerful, UX aware, and dead simple."
});

Package.on_use(function (api) {
  api.use('jquery', 'client');
  api.add_files('parsley.min.js', 'client');
  api.add_files('parsley.remote.min.js', 'client');
});

```

**Comment by amrali** [comment]
Yes, that's the correct package file. There's no call to jquery that I'm aware of there. When do you get that error?

**Comment by Neobii** [comment]
This is the error without that line: 
`Uncaught TypeError: Cannot read proiperty 'extend' of undefined parsley.remote.min.js:1`
The error pops when I add the package only, I haven't used it to validate anything yet, however when I added the jquery line the error stopped and I noticed that extend is $.extend from jquery.

**Comment by amrali** [comment]
#6 fixed this.
