### ISSUE TITLE
my onFieldError listener runs twice on fields of type email

### ISSUE THREAD

**Issue by clarkritchie** [amrali/parsleyjs-meteor#7]
This is great, thanks for wrapping up this JS library.

I am seeing the onFieldError listener execute twice on a single field failure.

Example:  A form which has one required field, e.g.

```
<input class="form-control" data-required="true" data-type="email" data-required-message="{{errorEmailRequired}}"...
```

The form is setup in the rendered callback:

```
parsleyOptions = {
  // Sets success and error class to Bootstrap class names
  successClass: '',//'has-success',
  errorClass: 'has-error has-feedback',
  trigger: 'change',

  // Bootsrap needs success/error class to be set on parent element
  errors: {
   classHandler: function ( elem, isRadioOrCheckbox ) {
     // specify where parsley error-success classes are set
     return $(elem).parents(".form-group");
   },
   // Set these to empty to make sure the default Parsley elements are not rendered
   errorsWrapper: '',
   errorElem: ''
  },

  listeners: {
   onFieldValidate: function ( elem ) {
     // remove the X from onFieldError if it's there
     elem.next( ".glyphicon-remove" ).remove();
   },

   onFieldError: function ( elem, constraints, parsleyField ) {
     // add the Bootstrap X glyphicon to the right side of the form element
     elem.after( '<span class="glyphicon glyphicon-remove form-control-feedback"></span>' );
     // access the data-required-message="xx" attribute on the field
     throwError( 000, "", elem.data('required-message' ) );
    },

    // onFieldSuccess: function(elem, constraints, parsleyField) {
    //   elem.next().remove( 'form-control-feedback' );
    // }
  }
};
```

```
Template.contactsAddOrEdit.rendered = function() {
  $( '#contactsAddOrEditForm' ).parsley( parsleyOptions );
};
```

When the field failure happens, onFieldError is called twice resulting in two errors to the user.  (throwError goes to a local errors collection, straight from the Meteor book example.)

![parsley1](https://cloud.githubusercontent.com/assets/385550/3331134/4cff582c-f7d9-11e3-93a8-b3bb103236ee.png)

Any thoughts?

**Comment by clarkritchie** [comment]
Update:  This seems to be only true when the field is data-type="email" -- I am not seeing the same behavior on regular text fields.

**Comment by amrali** [comment]
It's been a while since I did meteor, specially with the new version. I think modifying the HTML in `onFieldError` function causes a rerender which might be causing a second validation cycle of the form input field. Try to comment out the glyphicon span.

**Comment by clarkritchie** [comment]
Thanks.  I found more luck with the package parsleyjs-v2 on Atmosphere.
