### ISSUE TITLE
Can you post an example

### ISSUE THREAD

**Issue by rootedsoftware** [amrali/parsleyjs-meteor#8]
Can you post an example with the js file and the HTML files? I'm having trouble knowing if I've got all the pieces in place to really make this work. Also, so far many of the part of my validation aren't working at all or aren't working right. If you have any forms that also use bootstrap for the error styling that would be great to see. 

Thanks

**Comment by amrali** [comment]
http://parsleyjs.org/doc/examples.html does this help?

**Comment by rootedsoftware** [comment]
No, not really. I have already been using these examples and the form fields are not correctly being checked.

**Comment by rootedsoftware** [comment]
I think I figured out what was going on. 

I needed to add this line into the rendered area for my template. 

```
Template.name.rendered = function () {

  // Setup parsley form validation
  $('#donation_form').parsley();
}
```

Then add this into the form tag 
**data-parsley-validate**
